jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
    - continue-on-error: true
      name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      env:
        ASSETS_PASSWORD: ${{ secrets.ASSETS_PASSWORD }}
        SIGNING_KEY_7Z_PASSWORD: ${{ secrets.SIGNING_KEY_7Z_PASSWORD }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      name: Build with CI build script
      run: tools/ci/ci_build.sh
    - continue-on-error: true
      name: Upload build output
      uses: actions/upload-artifact@v1
      with:
        name: MCPELauncherApp
        path: MCPELauncherApp-release.apk
name: Build BlockLauncher
on:
  repository_dispatch:
    types: trigger-ga___build.yml
